---
- name: 'Build Sphinx search image'
  hosts: localhost
  tasks:
    # Gather facts
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}

    # Build sphinx docker image
    - name: 'Build image'
      when: ENABLE_SPHINXSEARCH == true
      docker_image:
        name: "sphinxsearch:latest"
        tag: "sphinxsearch"
        path: ./../../../services/sphinxsearch