---
- name: 'Build Sphinx search image'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Remove images'
      docker_image:
        name: "sphinxsearch:latest"
        force: yes
        tag: "sphinxsearch"
        state: absent
    - name: 'Build image'
      when: ENABLE_SPHINXSEARCH == true
      docker_image:
        name: "sphinxsearch:latest"
        tag: "sphinxsearch"
        path: ./../../../services/sphinxsearch