---
- name: 'Stop Sphinx search container'
  hosts: localhost
  tasks:
  - name: 'Include global vars'
    include_vars:
      dir: ./../../vars/global
  - name: 'Stop container'
    docker_container:
      name: "{{DOCKER_PREFIX}}_sphinxsearch"
      image: "sphinxsearch:latest"
      state: stopped
      force_kill: yes