---
- name: 'Connect to production server and run commands'
  hosts: "production"
  remote_user: "app_user"
  gather_facts: no
  tasks:
    - name: 'Run local-rebuild'
      command: "make local-rebuild inventory=production"
      args:
        chdir: "/home/app_user/project"