---
- name: 'Connect to production server and run commands'
  hosts: "production"
  remote_user: "app_user"
  gather_facts: no
  tasks:
    - name: 'Run local-restart'
      command: "make local-restart inventory=production"
      args:
        chdir: "/home/app_user/project"
    - name: 'Get docker status info'
      command: "make docker-status"
      args:
        chdir: "/home/app_user/project"
      register: docker_status
    - debug:
        var: docker_status.stdout_lines