---
- name: 'Connect to production server and run commands'
  hosts: "production"
  remote_user: "app_user"
  gather_facts: no
  tasks:
    - name: 'Run local-sphinx-rotate-all'
      command: "make local-sphinx-rotate-all inventory=staging"
      args:
        chdir: "/home/app_user/project"