---
- name: 'Add production_app host'
  hosts: "localhost"
  tasks:
  # Gather facts
  - name: 'Include global vars'
    include_vars:
      dir: ./../../vars/global
  - name: 'Include environment vars'
    include_vars:
      dir: ./../../vars/{{ env }}
  - add_host:
      env: "production"
      hostname: "production_app"
      ansible_connection: "ssh"
      ansible_host: "{{ PRODUCTION_SERVER_IP }}"
      ansible_port: "{{ PRODUCTION_SERVER_PORT }}"
      ansible_ssh_pass: "{{ SERVER_APP_USER_PASS }}"
      ansible_sudo_pass: "{{ SERVER_APP_USER_PASS }}"
      ansible_python_interpreter: "/usr/bin/python3"
- name: 'Connect to production server and run commands'
  hosts: "production_app"
  remote_user: "app_user"
  gather_facts: no
  tasks:
    - name: 'Run local-up'
      command: "make local-up inventory=production"
      args:
        chdir: "/home/app_user/project"
    - name: 'Get docker status info'
      command: "make docker-status"
      args:
        chdir: "/home/app_user/project"
      register: docker_status
    - debug:
        var: docker_status.stdout_lines
    - name: 'Apply chown command'
      file:
        path: '/home/app_user/project'
        owner: app_user
        group: app_user
        recurse: yes
      become: true
      become_user: root