---
- name: 'Destroy droplet machine'
  hosts: localhost
  tasks:
  - name: 'Run terraform destroy'
    terraform:
      project_path: "./../../../staging/{{ STAGING_PREFIX }}"
      binary_path: "./../terraform"
      state: absent
      force_init: yes
  - name: 'Create folder'
    file:
      path: ./../../../staging/{{ STAGING_PREFIX }}
      state: absent