- name: 'Export images files from app'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/{{item}}
        state: absent
      with_items:
        - images.zip
        - images
    - name: 'Create temp folder'
      file:
        path: ./../../../temp/images
        state: directory
    - name: 'Copy images to temp folder'
      copy:
        src: ./../../../app/storage/app/{{item}}
        dest: ./../../../temp/images
      with_items:
        - media
        - uploads
    - name: 'Create zip file'
      archive:
        path: ./../../../temp/images/
        dest: ./../../../temp/images.zip
        format: zip
    - name: 'Download dump file to bitbacket'
      when: dump_src == 'bitbacket'
      raw: "curl -X POST -s -u \"{{BITBACKET_USER}}:{{BITBACKET_PASSWORD}}\" {{BITBACKET_DOWNLOADS_PATH}} -F files=@./../../../temp/images.zip"
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/{{item}}
        state: absent
      with_items:
      - images