- name: 'Import images files to app'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Remove folders with old files'
      file:
        path: ./../../../app/storage/app/{{item}}
        state: absent
      with_items:
      - media
      - uploads
    - name: 'Create folders'
      file:
        path: ./../../../app/storage/app/{{item}}
        state: directory
      with_items:
        - media
        - uploads
    - name: 'Download images files from bitbucket'
      when: DUMP_SRC == 'bitbucket'
      raw: "curl -o ./../../../temp/images.zip -s -L  -u \"{{BITBACKET_USER}}:{{BITBACKET_PASSWORD}}\" https://api.bitbucket.org/2.0/repositories/{{ BITBACKET_VENDOR }}/{{ BITBACKET_PROJECT_NAME }}/downloads/images.zip"
    - name: 'Unzip file'
      unarchive:
        dest: ./../../../app/storage/app
        src: ./../../../temp/images.zip
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/{{item}}
        state: absent
      with_items:
      - images
      - images.zip