- name: 'Create app folder'
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Remove files in app'
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
      - ./../../../app/*
      - ./../../../app/.*
    - name: 'Find directories in app folder'
      find:
        paths: ./../../../app
        file_type: directory
      register: directory_list
    - name: 'Remove folders in app'
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ directory_list.files }}"

- name: 'Connect to docker workspace and install OctoberCMS'
  hosts: laradockoctober_workspace_1
  remote_user: laradock
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Install OctoberCMS from composer'
      raw: "composer create-project october/october /var/www/"
    - name: Generate env file
      raw: "php /var/www/artisan october:env"
    - name: Replace default mysql host
      lineinfile:
        path: /var/www/.env
        regexp: "^DB_HOST=localhost"
        line: "DB_HOST={{DOCKER_PREFIX}}_mysql"
    - name: Replace default mysql databese
      lineinfile:
        path: /var/www/.env
        regexp: "^DB_DATABASE=database"
        line: "DB_DATABASE={{DATABASE_NAME}}"
    - name: Replace default mysql user
      lineinfile:
        path: /var/www/.env
        regexp: "^DB_USERNAME=root"
        line: "DB_USERNAME={{DATABASE_USER}}"
    - name: Replace default mysql password
      lineinfile:
        path: /var/www/.env
        regexp: "^DB_PASSWORD="
        line: "DB_PASSWORD={{DATABASE_PASSWORD}}"
    - name: Create OctoberCMS tables
      raw: "php /var/www/artisan october:up"
    - name: Remove demo data
      raw: "php /var/www/artisan october:fresh"
    - name: Attach project ID
      copy:
        content: "/usr/bin/mysql -h{{DOCKER_PREFIX}}_mysql -u{{DATABASE_USER}} --password={{DATABASE_PASSWORD}} {{DATABASE_NAME}} -e \"INSERT INTO system_parameters (\\`namespace\\`,\\`group\\`,\\`item\\`,\\`value\\`) VALUES('system','project','id','{{PROJECT_ID}}');\""
        dest: "command-script.sh"
    - name: Run script
      raw: "bash command-script.sh"
    - name: Remove script file
      file:
        path: "command-script.sh"
        state: absent
    - name: Install OctoberCMS plugins
      raw: "php /var/www/artisan october:update"
    - name: Apply plugins migrations
      raw: "php /var/www/artisan october:up"
- name: 'Remove default files'
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Remove default OctoberCMS files'
      file:
        path: "./../../../app/{{ item }}"
        state: absent
      with_items:
        - .editorconfig
        - .gitignore
        - .gitattributes
        - .travis.yml
        - CHANGELOG.md
        - CONTRIBUTING.md
        - ISSUE_TEMPLATE.md
        - LICENSE
        - README.md
    - name: 'Clone basecode plugin'
      raw: 'git clone https://github.com/lovata/oc-basecode-plugin.git ./../../../app/plugins/lovata/basecode'
    - name: 'Remove git files form basecode plugin'
      file:
        path: "./../../../app/plugins/lovata/basecode/{{ item }}"
        state: absent
      with_items:
      - .git
      - .gitignore
- name: 'Connect to docker workspace and install basecode plugin'
  hosts: laradockoctober_workspace_1
  remote_user: laradock
  gather_facts: no
  tasks:
    - name: 'Apply migrations'
      raw: 'php artisan october:up'