---
- name: 'Add production_app host'
  hosts: localhost
  tasks:
  # Gather facts
  - name: 'Include global vars'
    include_vars:
      dir: ./../../vars/global
  - name: 'Include environment vars'
    include_vars:
      dir: ./../../vars/production
  - add_host:
      env: "production"
      hostname: "production_app"
      ansible_connection: "ssh"
      ansible_host: "{{ PRODUCTION_SERVER_IP }}"
      ansible_port: "{{ PRODUCTION_SERVER_PORT }}"
      ansible_ssh_pass: "{{ SERVER_APP_USER_PASS }}"
      ansible_sudo_pass: "{{ SERVER_APP_USER_PASS }}"
- name: 'Connect to production server and run commands'
  hosts: "production_app"
  remote_user: "app_user"
  gather_facts: no
  tasks:
  - name: 'Download content.zip archive'
    fetch:
      dest: ./../../../temp/
      src: /home/app_user/project/temp/content.zip
      flat: yes