- name: 'Import content files to app'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/{{item}}
        state: absent
      with_items:
      - content
    - name: 'Remove _temp folders'
      file:
        path: ./../../../app/themes/{{THEME_NAME}}/{{item}}_temp
        state: absent
      with_items:
      - content
      - meta
    - name: 'Create temp folder'
      file:
        path: ./../../../temp/content
        state: directory
    - name: 'Download content files from bitbacket'
      when: DUMP_SRC == 'bitbacket'
      raw: "curl -o ./../../../temp/content.zip -s -L  -u \"{{BITBACKET_USER}}:{{BITBACKET_PASSWORD}}\" https://api.bitbucket.org/2.0/repositories/{{ BITBACKET_VENDOR }}/{{ BITBACKET_PROJECT_NAME }}/downloads/content.zip"
    - name: 'Unzip file'
      unarchive:
        dest: ./../../../temp/content
        src: ./../../../temp/content.zip
    - name: 'Create folders'
      file:
        path: ./../../../app/themes/{{THEME_NAME}}/{{item}}
        state: directory
      with_items:
        - content
        - meta
    - name: 'Copy content to *_temp folder'
      copy:
        src: ./../../../app/themes/{{THEME_NAME}}/{{item}}
        dest: ./../../../app/themes/{{THEME_NAME}}/{{item}}_temp
      with_items:
      - content
      - meta
    - name: 'Copy content from temp folder'
      copy:
        src: ./../../../temp/content/{{item}}
        dest: ./../../../app/themes/{{THEME_NAME}}/
      with_items:
      - content
      - meta
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/{{item}}
        state: absent
      with_items:
      - content
      - content.zip