---
- name: 'Build MySQL image'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: 'Remove images'
      docker_image:
        name: "mysql:{{ MYSQL_VERSION }}"
        force: yes
        tag: "{{ MYSQL_VERSION }}"
        state: absent
    - name: 'Build image'
      when: DATABASE_TYPE == 'mysql'
      docker_image:
        name: "mysql:{{ MYSQL_VERSION }}"
        tag: "{{ MYSQL_VERSION }}"
        path: ./../../../services/mysql
        buildargs:
          MYSQL_VERSION: "{{ MYSQL_VERSION }}"
          TZ: "{{ WORKSPACE_TIMEZONE }}"