- name: 'Download dump files from staging'
  when: DUMP_SRC == 'staging'
  import_playbook: download-images-dump-staging.yml
- name: 'Download dump files from production'
  when: DUMP_SRC == 'production'
  import_playbook: download-images-dump-production.yml
- name: 'Import dump file to local db'
  hosts: localhost
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Download dump file from bitbucket'
      when: DUMP_SRC == 'bitbucket'
      raw: "curl -o ./../../../temp/db.zip -s -L  -u \"{{BITBACKET_USER}}:{{BITBACKET_PASSWORD}}\" https://api.bitbucket.org/2.0/repositories/{{ BITBACKET_VENDOR }}/{{ BITBACKET_PROJECT_NAME }}/downloads/db.zip"
    - name: 'Create temp folder'
      file:
        path: ./../../../temp/db
        state: directory
    - name: 'Unzip file'
      unarchive:
        dest: ./../../../temp/db
        src: ./../../../temp/db.zip

- name: 'Connect to docker workspace and apply dump'
  hosts: laradockoctober_workspace_1
  remote_user: laradock
  tasks:
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: Apply dump
      raw: "/usr/bin/mysql -h{{DOCKER_PREFIX}}_mysql -u{{DATABASE_USER}} --password={{DATABASE_PASSWORD}} {{DATABASE_NAME}} < /home/laradock/temp/db/db.sql >> /dev/null 2>&1"
    - name: 'Apply migrations'
      raw: "php artisan october:up"
    - name: "Reset admin password"
      when: env != 'production'
      raw: "php artisan basecode:reset_admin_password"
    - name: Reset mysql settings
      when: env != 'production'
      template:
        src: ./../../templates/mysql/{{env}}-reset-mail-settings.sh.j2
        dest: reset-mail-settings.sh
    - name: Run script
      when: env != 'production'
      raw: "bash reset-mail-settings.sh"
    - name: Remove script file
      when: env != 'production'
      file:
        path: "reset-mail-settings.sh"
        state: absent

- name: 'Remove dump file'
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 'Remove temp folder'
      file:
        path: ./../../../temp/db
        state: absent
    - name: 'Remove zip file'
      file:
        path: ./../../../temp/db.zip
        state: absent
