---
- name: 'Get droplet IP'
  hosts: localhost
  tasks:
  # Gather facts
  - name: 'Include global vars'
    include_vars:
      dir: ./../../vars/global
  - name: 'Include environment vars'
    include_vars:
      dir: ./../../vars/{{ env }}
  - name: "Get droplet IP"
    command: "./../terraform output ip"
    args:
        chdir: "./../../../staging/{{ STAGING_PREFIX }}"
    register: terraform_config
  - add_host:
      env: "staging"
      hostname: "staging"
      ansible_connection: "ssh"
      ansible_host: "{{ terraform_config.stdout }}"
      ansible_port: 22
      ansible_python_interpreter: "/usr/bin/python3"
- name: 'Connect to droplet and run commands'
  hosts: "staging"
  remote_user: "app_user"
  tasks:
    # Gather facts
    - name: 'Include global vars'
      include_vars:
        dir: ./../../vars/global
    - name: 'Include environment vars'
      include_vars:
        dir: ./../../vars/{{ env }}
    - name: "Git pull"
      git:
        repo: "https://{{ BITBACKET_USER }}:{{ BITBACKET_PASSWORD }}@bitbucket.org/{{ BITBACKET_VENDOR }}/{{ BITBACKET_PROJECT_NAME }}.git"
        dest: "/home/app_user/project"
        version: "{{ GIT_VERSION }}"
        update: yes
        force: yes
    - name: 'Run local-up'
      command: "make local-up inventory=staging prefix={{ STAGING_PREFIX }}"
      args:
        chdir: "/home/app_user/project"
    - name: 'Get docker status info'
      command: "make docker-status"
      args:
        chdir: "/home/app_user/project"
      register: docker_status
    - debug:
        var: docker_status.stdout_lines
    - name: 'Run local-composer-install'
      when: WITHOUT_COMPOSER == true
      command: "make local-composer-install inventory=staging"
      args:
        chdir: "/home/app_user/project"
    - name: 'Run local-october-up'
      command: "make local-october-up inventory=staging"
      args:
        chdir: "/home/app_user/project"
    - name: 'Run local-npm-prod'
      command: "make local-npm-prod inventory=staging"
      args:
        chdir: "/home/app_user/project"